import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NuqsProvider from "@/providers/NuqsProvider";
import NextAuth from "next-auth";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/providers/StoreProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#f7fafe] antialiased`}
      >
        <ThemeProvider>
          <NextAuthProvider>
            <NuqsProvider>
              <StoreProvider>
                <ReactQueryProvider>
                  <Navbar />
                  {children}
                  <Footer />
                </ReactQueryProvider>
                <ToastContainer />
              </StoreProvider>
            </NuqsProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
